import { ContentType } from "./types.ts";

export const aboutus: ContentType = {
  tr: {
    title: "Biz Kimiz? Ne Yaparız?",
    text: "Türkiye, isabetli devlet politikaları, özel sektörde yapılan doğru yatırımlar ve gelişen teknolojiye hızlı bir şekilde uyum neticesinde; eğitim, sağlık, turizm ve yatirim gibi birçok alanda, rakiplerine göre öncü ve lider konumda olup, yükselen bir değer ve marka haline gelerek cazibe merkezi haline dönüşmüştür. Ülkemizin, 66 ülkeye 5 saatlik uçuş mesafesinde olması, doğal zenginlikleri, kültürel farklılıkları, bir çok medeniyete ev sahipliği yapması ve tüm dünyaya goşgörü ile gönül köprüsü kurmayı hedeflemesi de bu durumu desteklemektedir. Bu bağlamda “World & Turkey” olarak, hizmet sektöründe yenilikçi bir bakış açısıyla, dürüstlük, güven ve samimiyeti esas alarak; en iyi hizmeti, en doğru şekilde sizlere ulaştırma hedefi ve gayreti içerisindeyiz. Bünyemizde çalışan profesyonel, dinamik ve güçlü bir ekiple; “Eğitim”, “Sağlık” ve “Yatırım Danışmanlığı” alanlarında, müşteri memnuniyetini ve kaliteli hizmet anlayışını her şeyden önde tutarak, bu ilke doğrultusunda ihtiyaçlarınızın tümüne en hızlı ve en uygun şekilde cevap verebilmek için gerekli tüm çalışmaları yapmaya her gün, her saat devam etmekteyiz.",
  },
  en: {
    title: "Who Are We? What Do We Do?",
    text: "Turkey, as a result of prudent state policies, correct investments in the private sector, and quick adaptation to developing technology; has become a leading and pioneering value and brand in many areas such as education, health, tourism, and investment, turning into a center of attraction. Our country’s proximity, being within a 5-hour flight distance from 66 countries, its natural wealth, cultural diversity, hosting many civilizations, and its aim to build bridges of understanding with the world also supports this situation. In this context, as “World & Turkey,” we strive to provide the best service to you with honesty, trust, and sincerity, based on an innovative perspective in the service sector. With a professional, dynamic, and strong team; in the areas of “Education,” “Health,” and “Investment Consulting,” we continue our efforts every day and every hour to meet all your needs in the fastest and most suitable way, prioritizing customer satisfaction and high-quality service.",
  },
  ar: {
    title: "من نحن؟ ماذا نفعل؟",
    text: "تركيا، بفضل السياسات الحكومية الحكيمة، والاستثمارات الصحيحة في القطاع الخاص، والتكيف السريع مع التكنولوجيا المتطورة؛ أصبحت في مقدمة المجالات مثل التعليم والصحة والسياحة والاستثمار، وأصبحت علامة تجارية بارزة وجذابة، تتحول إلى مركز جذب.\n\nموقع بلادنا، الذي يبعد ٥ ساعات طيران عن ٦٦ دولة، وثرواتها الطبيعية، واختلافاتها الثقافية، واستضافتها للعديد من الحضارات، وسعيها لبناء جسر من التفاهم مع العالم، يدعم هذه الحالة.\n\nفي هذا السياق، كـ “World & Turkey”، نسعى في قطاع الخدمات برؤية مبتكرة، مع الالتزام بالنزاهة والثقة والصدق؛ لتحقيق أفضل خدمة وتقديمها إليكم بأفضل طريقة.\n\nبفريق محترف، ديناميكي وقوي؛ في مجالات “التعليم”، و”الصحة”، و”استشارات الاستثمار”، نواصل العمل على تلبية جميع احتياجاتكم بسرعة وبدقة، مع الحفاظ على رضا العملاء وفهم الخدمة الجيدة كأولوية قصوى.",
  },
  ru: {
    title: "Кто мы? Что мы делаем?",
    text: "Турция, благодаря разумной государственной политике, правильным инвестициям в частный сектор и быстрой адаптации к развивающимся технологиям; стала ведущей и пионерской страной в таких областях, как образование, здравоохранение, туризм и инвестиции, и превратилась в привлекательный центр. Расположение нашей страны, находящейся в 5 часах лета от 66 стран, её природные богатства, культурное разнообразие, гостеприимство множества цивилизаций и стремление построить мосты понимания с миром также поддерживает эту ситуацию. В этом контексте, как «World & Turkey», мы стремимся предоставить вам лучший сервис с честностью, доверием и искренностью, опираясь на инновационный подход в сфере услуг. С профессиональной, динамичной и сильной командой; в областях «Образование», «Здравоохранение» и «Инвестиционное консультирование», мы продолжаем наши усилия каждый день и каждый час, чтобы удовлетворить все ваши потребности самым быстрым и подходящим образом, приоритетизируя удовлетворение клиентов и качественное обслуживание.",
  },
  fr: {
    title: "Qui sommes-nous? Que faisons-nous?",
    text: "La Turquie, grâce à des politiques d'État prudentes, des investissements corrects dans le secteur privé et une adaptation rapide aux technologies en développement; est devenue une valeur et une marque leader et pionnière dans de nombreux domaines tels que l'éducation, la santé, le tourisme et l'investissement, devenant un centre d'attraction. La proximité de notre pays, étant à une distance de vol de 5 heures de 66 pays, sa richesse naturelle, sa diversité culturelle, accueillant de nombreuses civilisations, et son objectif de construire des ponts de compréhension avec le monde soutiennent également cette situation. Dans ce contexte, en tant que “World & Turkey”, nous nous efforçons de vous offrir le meilleur service avec honnêteté, confiance et sincérité, basé sur une perspective innovante dans le secteur des services. Avec une équipe professionnelle, dynamique et forte; dans les domaines de l'éducation, de la santé et du conseil en investissement, nous continuons nos efforts chaque jour et à chaque heure pour répondre à tous vos besoins de la manière la plus rapide et la plus appropriée, en donnant la priorité à la satisfaction du client et à un service de haute qualité.",
  },
};
